# Base server group
server.address=127.0.0.1
server.port=8080
server.error.include-message=always

# Logging
logging.level.org.zalando.logbook=TRACE

# ================
# Spring framework
# ================

# Spring data
spring.sql.init.mode=always
spring.datasource.url=jdbc:h2:file:./database/filmoratedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password 

